### ISSUE TITLE
How can I run inference with my own video?

### ISSUE THREAD

**Issue by jet981217** [e-apostolidis/PGL-SUM#3]
How can I extract the features for my own video so that I can put it in inference.py?

**Comment by mpalaourg** [comment]
Hello @jet981217,
this repo doesn't support inferencing for your own video. It is possible if you get the `frame_features` via GoogleNet and by running -for a specific model- the `inference.py` script.

However, we have a web service [here](http://multimedia2.iti.gr/videosummarization/service/start.html), which lets you submit videos in various formats and generate summaries for use in various social media channels. I hope this helps!

**Comment by jet981217** [comment]
@mpalaourg  Thank you so much for the swift answer! This will help a lot for me!
